apiVersion: v1alpha1
sts-region: ap-southeast-2
discovery:
  jobs:
    - type: AWS/ECS
      regions: [ap-southeast-2]
      period: 300
      length: 300
      metrics:
        - name: CPUReservation
          statistics:
            - Average
        - name: MemoryReservation
          statistics:
            - Average
        - name: CPUUtilization
          statistics:
            - Average
        - name: MemoryUtilization
          statistics:
            - Average
    - type: AWS/EC2
      regions: [ap-southeast-2]
      metrics:
        - name: CPUUtilization
          statistics:
            - Average
    - type: AWS/S3
      regions: [ap-southeast-2]
      period: 864000
      length: 864000
      metrics:
        - name: NumberOfObjects
          statistics:
            - Average
        - name: BucketSizeBytes
          statistics:
            - Average
