---
apiVersion: v1alpha1
discovery:
  jobs:
    - length: 300
      metrics:
        - name: CPUReservation
          statistics:
            - Average
        - name: MemoryReservation
          statistics:
            - Average
        - name: CPUUtilization
          statistics:
            - Average
        - name: MemoryUtilization
          statistics:
            - Average
      period: 300
      regions: [ap-southeast-2]
      type: AWS/ECS
    - length: 864000
      metrics:
        - name: NumberOfObjects
          statistics: [Average, Minimum, Maximum, Sum]
        - name: BucketSizeBytes
          statistics: [Average, Minimum, Maximum, Sum]
      period: 864000
      regions: [ap-southeast-2]
      type: AWS/S3
    - metrics:
        - length: 60000
          name: HealthCheckStatus
          period: 60000
          statistics: [Average, Minimum, Maximum, Sum]
        - length: 60000
          name: HealthCheckPercentageHealthy
          period: 60000
          statistics: [Average, Minimum, Maximum, Sum]
      regions: [us-east-1]
      type: AWS/Route53
    - metrics:
        - length: 60000
          name: BytesDownloaded
          period: 60000
          statistics: [Sum]
        - length: 60000
          name: BytesUploaded
          # dimensionNameRequirements: [DistributionId, Region]
          period: 60000                                                                                                                                                                                                            
          statistics: [Sum]
        - name: 4xxErrorRate
          statistics: [Sum]
          # dimensionNameRequirements: [DistributionId, Region]
        - name: 5xxErrorRate
          statistics: [Sum]
        - name: TotalErrorRate
          statistics: [Sum]
      regions: [us-east-1]
      dimensionNameRequirements: [DistributionId, Region]

      type: AWS/CloudFront
sts-region: ap-southeast-2
#   metrics:
#     - name: Invocations
#       statistics: [Sum]
#     - name: Errors
#       statistics: [Sum]
#     - name: Throttles
#       statistics: [Sum]
#     - name: Duration
#       statistics: [Average, Maximum, Minimum, p90]
# - type: AWS/EC2
#   regions: [ap-southeast-2]
#     - name: RequestCount
#       statistics: [Average]
#     - name: TargetResponseTime
#       statistics: [Average]
#     - name: ActiveConnectionCount
#       statistics: [Sum]
#     - name: NewConnectionCount
#       statistics: [Sum]
#     - name: RejectedConnectionCount
#       statistics: [Sum]
#     - name: TargetConnectionErrorCount
#       statistics: [Sum]
#     - name: IPv6RequestCount
#       statistics: [Sum]
#   metrics:
#     - name: HealthyHostCount
#       statistics: [Sum]
#     - name: UnHealthyHostCount
#       statistics: [Sum]
#     - name: RequestCountPerTarget
#       statistics: [Sum]
#     - name: NonStickyRequestCount
#       statistics: [Sum]
#     - name: HTTPCode_Target_2XX_Count
#       statistics: [Sum]
#     - name: HTTPCode_Target_3XX_Count
#       statistics: [Sum]
#     - name: HTTPCode_Target_4XX_Count
#       statistics: [Sum]
#     - name: HTTPCode_Target_5XX_Count
#       statistics: [Sum]
#     - name: HTTPCode_ELB_3XX_Count
#       statistics: [Sum]
#     - name: HTTPCode_ELB_4XX_Count
#       statistics: [Sum]
#     - name: HTTPCode_ELB_5XX_Count
#       statistics: [Sum]
#     - name: ProcessedBytes
#       statistics: [Sum]
#     - name: IPv6ProcessedBytes
#       statistics: [Sum]
#     - name: ConsumedLCUs
#       statistics: [Average]
#     - name: ClientTLSNegotiationErrorCount
#       statistics: [Sum]
#     - name: TargetTLSNegotiationErrorCount
#       statistics: [Sum]
#     - name: RuleEvaluations
#       statistics: [Sum]
# - type: AWS/Lambda
#   regions: [ap-southeast-2]
#   period: 300
#   length: 300
# - type: AWS/ApplicationELB
#   regions: [ap-southeast-2]
#   period: 300
#   length: 300
#   metrics:
#     - name: CPUUtilization
#       statistics:
#         - Average#         - Average
#         period: 60000
#         length: 60000
#       - name: HealthCheckPercentageHealthy
#         statistics:
# static:
#   - namespace: AWS/Route53
#     name: techscrum-frontend-rt53
#     regions:
#       - us-east-1
#     customTags:
#       - key: Name
#         value: techsrum-http-health-check
#     metrics:
#       - name: HealthCheckStatus
#         statistics:
#         - Average
#         period: 60000
#         length: 60000
